# Script B: make the grouped circular bar plot
#
# This script expects the output generated by Script A:
#   data/mock_data.csv
#
# Required columns:
#   group    - group used to organise bars into sections
#   category - label for each individual bar
#   value    - numeric bar height
#
# Run this script from the repository root after running Script A.

library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(readr)

input_file <- file.path("data", "mock_data.csv")
output_file <- file.path("output", "circular_barplot.png")

# -----------------------------------------------------------------------------
# USER SETTINGS: colours, spacing and label positions
# -----------------------------------------------------------------------------

# Number of empty bar positions inserted between groups.
empty_bar <- 3

# Colours used for each group.
# The names MUST match the values in the 'group' column.
# Edit the hexadecimal colour codes here to use another palette.
group_colours <- c(
  "Group A" = "#4f2a86",
  "Group B" = "#22b16d",
  "Group C" = "#e66b63",
  "Group D" = "#2f5573"
)

# Category labels around the outside of the circle.
category_label_offset <- 1       # radial distance above the top of each bar
category_label_wrap <- 30        # wrap long labels after approximately N characters
category_label_size <- 3

# Group labels inside the circle.
# x/nudge controls the angular position; y controls distance from the centre.
group_label_y <- -3
group_label_size <- 4

group_label_nudge_x <- c(
  "Group A" = 0,
  "Group B" = 0,
  "Group C" = 0,
  "Group D" = 0
)

# Horizontal justification can be adjusted group by group if labels need
# fine-tuning after they are placed around the circle.
group_label_hjust <- c(
  "Group A" = 0.2,
  "Group B" = 1.0,
  "Group C" = 0.5,
  "Group D" = 0.2
)

# Position of the short baseline underneath each group.
baseline_y <- -0.5

# Radial grid and plotting limits used for the supplied mock example.
# Change these if your values use a different range.
y_ticks <- c(2, 4, 6, 8)
y_min <- -10
y_max <- 12

# -----------------------------------------------------------------------------
# READ AND CHECK DATA
# -----------------------------------------------------------------------------

if (!file.exists(input_file)) {
  stop(
    "Input file not found: ", input_file,
    "\nRun R/A_generate_mock_data.R first."
  )
}

raw_data <- read_csv(input_file, show_col_types = FALSE)

required_columns <- c("group", "category", "value")
missing_columns <- setdiff(required_columns, names(raw_data))

if (length(missing_columns) > 0) {
  stop(
    "Input data are missing required column(s): ",
    paste(missing_columns, collapse = ", ")
  )
}

if (!is.numeric(raw_data$value)) {
  stop("Column 'value' must be numeric.")
}

if (any(is.na(raw_data$group)) || any(is.na(raw_data$category))) {
  stop("Columns 'group' and 'category' cannot contain missing values.")
}

group_levels <- unique(raw_data$group)

# Make sure every group in the data has a colour and label-position setting.
missing_colours <- setdiff(group_levels, names(group_colours))
if (length(missing_colours) > 0) {
  stop(
    "Add colours for these group(s) in 'group_colours': ",
    paste(missing_colours, collapse = ", ")
  )
}

# If users add new groups but do not specify label fine-tuning, use sensible
# defaults rather than failing.
missing_nudge <- setdiff(group_levels, names(group_label_nudge_x))
if (length(missing_nudge) > 0) {
  group_label_nudge_x[missing_nudge] <- 0
}

missing_hjust <- setdiff(group_levels, names(group_label_hjust))
if (length(missing_hjust) > 0) {
  group_label_hjust[missing_hjust] <- 0.5
}

# -----------------------------------------------------------------------------
# PREPARE DATA FOR THE CIRCULAR LAYOUT
# -----------------------------------------------------------------------------

plot_data <- raw_data %>%
  transmute(
    group = factor(group, levels = group_levels),
    individual = as.character(category),
    value = as.numeric(value),
    is_gap = FALSE
  ) %>%
  arrange(group, value, individual)

# Add blank positions after each group to create visible gaps between sections.
empty_rows <- tibble(
  group = factor(
    rep(group_levels, each = empty_bar),
    levels = group_levels
  ),
  individual = NA_character_,
  value = NA_real_,
  is_gap = TRUE
)

plot_data <- bind_rows(plot_data, empty_rows) %>%
  arrange(group, is_gap, value, individual) %>%
  mutate(id = row_number())

number_of_bars <- nrow(plot_data)

# -----------------------------------------------------------------------------
# CATEGORY LABEL POSITIONS
# -----------------------------------------------------------------------------
#
# Each label is rotated according to its angular position around the circle.
# Labels on the left side are flipped by 180 degrees and right-justified so
# that all text remains readable rather than appearing upside down.

label_data <- plot_data %>%
  mutate(
    angle_raw = 90 - 360 * (id - 0.5) / number_of_bars,
    hjust = if_else(angle_raw < -90, 1, 0),
    angle = if_else(angle_raw < -90, angle_raw + 180, angle_raw),
    label = str_wrap(individual, width = category_label_wrap)
  )

# -----------------------------------------------------------------------------
# GROUP LABEL POSITIONS
# -----------------------------------------------------------------------------

base_data <- plot_data %>%
  group_by(group) %>%
  summarise(
    start = min(id),
    end = max(id) - empty_bar,
    title = (start + end) / 2,
    .groups = "drop"
  ) %>%
  mutate(
    group_chr = as.character(group),
    title_x = title + unname(group_label_nudge_x[group_chr]),
    label_hjust = unname(group_label_hjust[group_chr])
  )

# Grid lines are drawn separately within each group section.
grid_data <- crossing(base_data, y = y_ticks)

# Put radial scale values in the centre of each gap following a group.
axis_data <- crossing(
  base_data %>% mutate(axis_x = end + (empty_bar + 1) / 2),
  y = y_ticks
) %>%
  mutate(label = as.character(y))

# -----------------------------------------------------------------------------
# DRAW PLOT
# -----------------------------------------------------------------------------

p <- ggplot(plot_data, aes(x = id, y = value, fill = group)) +

  # Radial grid lines. Draw these first so the bars appear over them.
  geom_segment(
    data = grid_data,
    aes(x = start, xend = end, y = y, yend = y),
    inherit.aes = FALSE,
    colour = "grey80",
    linewidth = 0.3
  ) +

  # Bars.
  geom_col(width = 0.9, alpha = 0.5, na.rm = TRUE) +

  # Category labels around the outside.
  # Change category_label_offset above to move labels closer to/further from bars.
  geom_text(
    data = label_data %>% filter(!is.na(individual)),
    aes(
      x = id,
      y = value + category_label_offset,
      label = label,
      angle = angle,
      hjust = hjust
    ),
    inherit.aes = FALSE,
    colour = "black",
    alpha = 0.6,
    size = category_label_size,
    fontface = "plain"
  ) +

  # Short baseline marking each group.
  geom_segment(
    data = base_data,
    aes(x = start, xend = end, y = baseline_y, yend = baseline_y),
    inherit.aes = FALSE,
    colour = "black",
    alpha = 0.8,
    linewidth = 0.8
  ) +

  # Group labels inside the circle.
  # Fine-tune group_label_y, group_label_nudge_x and group_label_hjust above.
  geom_text(
    data = base_data,
    aes(
      x = title_x,
      y = group_label_y,
      label = group,
      hjust = label_hjust
    ),
    inherit.aes = FALSE,
    colour = "black",
    alpha = 0.8,
    size = group_label_size,
    fontface = "bold"
  ) +

  # Radial scale values.
  geom_text(
    data = axis_data,
    aes(x = axis_x, y = y, label = label),
    inherit.aes = FALSE,
    colour = "grey45",
    size = 2.8
  ) +

  # Explicit colour mapping. This is what links the named colours above
  # to the corresponding groups in the data.
  scale_fill_manual(values = group_colours) +

  scale_x_continuous(
    limits = c(0.5, number_of_bars + 0.5),
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    limits = c(y_min, y_max),
    expand = c(0, 0)
  ) +
  coord_polar() +
  theme_void() +
  theme(
    legend.position = "none",
    plot.margin = margin(15, 15, 15, 15)
  )

print(p)

dir.create("output", showWarnings = FALSE)

ggsave(
  filename = output_file,
  plot = p,
  width = 7,
  height = 7,
  dpi = 1200,
  bg = "transparent"
)

message("Plot written to ", output_file)
